apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
spec:
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
      - name: loginapp
        image: thanhlam2k4/loginapp:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: loginapp-svc
spec:
  selector:
    app: loginapp
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

